### PR TITLE
Update runtime and application

### PR DESCRIPTION
**Pull request by lionirdeadman**
Changing the runtime because 5.12 is EOL
Updating application to newer release with the appdata
Adding upstream cmake-fix.patch for cmake 3.20.x
Removing -Werror because there's only warning which could be ignored

The only warning present which has no fix upstream : 
```
../common/src/Model/Brush.cpp:264:37: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  264 |                         return kdl::void_success;
      |                                     ^~~~~~~~~~~~
```

Runtime output:
```
Gtk-Message: 16:15:51.174: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:15:51.174: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Renderer info: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.12.9-300.fc34.x86_64, LLVM 11.1.0) version 4.6 (Compatibility Profile) Mesa 21.1.1 (git-abac12bc75) from AMD
Depth buffer bits: 24
Multisampling enabled
Adding file system path /app/share/TrenchBroom/defaults/assets
Creating new document
Loaded entity definition file dday.fgd
Loading palette file pics/colormap.pcx
Could not load palette file 'pics/colormap.pcx': File not found: 'pics/colormap.pcx'
Renderer info: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.12.9-300.fc34.x86_64, LLVM 11.1.0) version 4.6 (Compatibility Profile) Mesa 21.1.1 (git-abac12bc75) from AMD
Depth buffer bits: 24
Multisampling enabled
Adding file system path /app/share/TrenchBroom/defaults/assets
Creating new document
Unquoted float default value 1.0 (line 223, column 40)
Unquoted float default value 2.0 (line 334, column 56)
Unquoted float default value 0.5 (line 335, column 108)
Unquoted float default value 4.0 (line 336, column 72)
Unquoted float default value 0.10 (line 337, column 69)
Unquoted float default value 0.20 (line 340, column 92)
Unquoted float default value 6.0 (line 358, column 53)
Unquoted float default value 2.0 (line 359, column 62)
Unquoted float default value 0.0 (line 361, column 64)
Unquoted float default value 1.0 (line 362, column 69)
Unquoted float default value 0 (line 396, column 62)
Unquoted float default value 4.0 (line 451, column 75)
Unquoted float default value 12.0 (line 452, column 76)
Unquoted float default value 1.0 (line 627, column 96)
Unquoted float default value 1.0 (line 810, column 152)
Unquoted float default value 1.0 (line 813, column 81)
Unquoted float default value 1.0 (line 815, column 60)
Unquoted float default value 1.0 (line 816, column 74)
Unquoted float default value 2.0 (line 943, column 77)
Unquoted float default value 0.0 (line 944, column 125)
Unquoted float default value 0.2 (line 1002, column 77)
Unquoted float default value 0.2 (line 1101, column 77)
Unquoted float default value 0.10 (line 1312, column 78)
Unquoted float default value 1.0 (line 1342, column 48)
Unquoted float default value 1.0 (line 1344, column 31)
Unquoted float default value 0.20 (line 3, column 59)
Unquoted float default value 1.0 (line 27, column 48)
Loaded entity definition file Episode 1.fgd
```
Not sure if anything here is bad.

### CODE REVIEW

**Comment by kduske** [comment]
> Changing the runtime because 5.12 is EOL
> Updating application to newer release with the appdata
> Adding upstream cmake-fix.patch for cmake 3.20.x
> Removing -Werror because there's only warning which could be ignored
> 
> The only warning present which has no fix upstream :
> 
> ```
> ../common/src/Model/Brush.cpp:264:37: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>   264 |                         return kdl::void_success;
>       |                                     ^~~~~~~~~~~~
> ```

Which compiler is this? I think this is a spurious warning. Also, I'm surprised -- which commit are you compiling here? I have only one usage of `kdl::void_success` in `Brush.cpp` and it's in a completely different line.

> 
> Runtime output:
> 
> ...
> 
> Not sure if anything here is bad.

Runtime output looks fine!

**Comment by lionirdeadman** [comment]
> > Changing the runtime because 5.12 is EOL
> > Updating application to newer release with the appdata
> > Adding upstream cmake-fix.patch for cmake 3.20.x
> > Removing -Werror because there's only warning which could be ignored
> > The only warning present which has no fix upstream :
> > ```
> > ../common/src/Model/Brush.cpp:264:37: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> >   264 |                         return kdl::void_success;
> >       |                                     ^~~~~~~~~~~~
> > ```
> 
> Which compiler is this? I think this is a spurious warning. Also, I'm surprised -- which commit are you compiling here? I have only one usage of `kdl::void_success` in `Brush.cpp` and it's in a completely different line.

This is GCC 10.2.0
The commit is 532e1b4d505d5aaf710ba09192d9fbaeb963010a (which is the latest commit for 2021.1) as per the manifest which does match the warning location.

**Comment by Sinihopea** [comment]
Looks fine to me. Also sorry that I'm two weeks late to this. I'm usually at least somewhat faster to reply to things addressed for me. And thank you very much for your contribution. I haven't had time to take proper care of this as of late due to variety of reasons.

**Review by Sinihopea — COMMENTED** [review]
Thanks for updating this. I hadn't noticed for example that the runtime was out of date. Looks good to me. That CMake patch is interesting.

**Pull request merged**
